export const cakes = [
  {
    id: 1,
    category: "Birthday",
    name: "Custom Birthday Cake",
    price: 90,
    image: "/images/cake/bdcj5f.jpeg",
    featured: true,
    rating: 5,
    reviews: 24,
    description:
      "Personalised birthday cake designed for kids and family celebrations. Colours, theme, name and age can be customised.",
    sizes: ["1kg", "2kg", "3kg", "4kg+"],
    flavours: ["Chocolate", "Vanilla", "Red Velvet", "Butter Cake"],
    pickup: true,
    delivery: true,
    notice: "2–3 days notice required",
  },
  {
    id: 2,
    category: "Birthday",
    name: "Princess Birthday Cake",
    price: 95,
    image: "/images/cake/bdcr5.jpeg",
    featured: false,
    rating: 5,
    reviews: 18,
    description:
      "A beautiful princess-themed cake made for magical birthday celebrations.",
    sizes: ["1kg", "2kg", "3kg", "4kg+"],
    flavours: ["Chocolate", "Vanilla", "Ribbon", "Butter Cake"],
    pickup: true,
    delivery: true,
    notice: "2–3 days notice required",
  },
  {
    id: 3,
    category: "Birthday",
    name: "Car Theme Cake",
    price: 95,
    image: "/images/cake/bdcr2.png",
    featured: false,
    rating: 5,
    reviews: 16,
    description:
      "A fun car-themed cake for kids who love racing, vehicles and colourful designs.",
    sizes: ["1kg", "2kg", "3kg", "4kg+"],
    flavours: ["Chocolate", "Vanilla", "Red Velvet", "Butter Cake"],
    pickup: true,
    delivery: true,
    notice: "2–3 days notice required",
  },
  {
    id: 4,
    category: "Cupcakes",
    name: "Cupcakes Bouquet",
    price: 35,
    image: "/images/cake/bdcd35.png",
    featured: true,
    rating: 5,
    reviews: 20,
    description:
      "Elegant cupcake bouquet arranged beautifully for birthdays, gifts and celebrations.",
    sizes: ["6 pcs", "12 pcs", "24 pcs"],
    flavours: ["Chocolate", "Vanilla", "Red Velvet", "Butter Cake"],
    pickup: true,
    delivery: true,
    notice: "1–2 days notice required",
  },
];